# Generated by Django 3.2.7 on 2021-11-19 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211118_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 10, 33, 8, 732286, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MyBookings',
        ),
    ]
