# Generated by Django 3.2.7 on 2021-11-21 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20211121_1627'),
        ('users', '0015_alter_activation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='selection.department'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 15, 4, 28, 396599, tzinfo=utc)),
        ),
    ]
