# Generated by Django 3.2.7 on 2021-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_office_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor_levels',
            field=models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4')], max_length=2),
        ),
    ]
