# Generated by Django 3.2.7 on 2021-10-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zone', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zones.zone')),
            ],
        ),
    ]
