# Generated by Django 3.2.7 on 2021-09-15 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('floor_equipment', models.CharField(choices=[('X', 'X'), ('K', 'K'), ('R', 'R')], max_length=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=0)),
                ('office_equipment', models.CharField(choices=[('D', 'D'), ('P', 'D')], max_length=1)),
                ('office_location', models.CharField(choices=[('wsd', 'wsd'), ('wdd', 'wdd'), ('isd', 'isd'), ('idd', 'idd')], max_length=3)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.floor')),
                ('owner_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
