# Generated by Django 3.2.7 on 2021-09-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='zone',
            new_name='zone_id',
        ),
    ]
