# Generated by Django 3.2.7 on 2021-09-23 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_rename_zone_office_zone_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='zone_id',
            new_name='zone',
        ),
        migrations.AlterField(
            model_name='floorzonemapping',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='officezonemapping',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
