# Generated by Django 3.2.7 on 2021-11-17 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_alter_floor_floor_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'office', 'start_date', 'end_date'), ('user', 'start_date', 'end_date')},
        ),
    ]
