# Generated by Django 3.2.7 on 2021-11-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
