# Generated by Django 3.2.7 on 2021-10-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zone_location', models.CharField(choices=[('Z1', 'Zone one'), ('Z2', 'Zone two'), ('Z3', 'Zone three'), ('Z4', 'Zone four'), ('Z5', 'Zone five'), ('Z6', 'Zone six'), ('Z7', 'Zone seven'), ('Z8', 'Zone eight')], max_length=20)),
                ('floor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='floors.floor')),
            ],
        ),
    ]
