# Generated by Django 3.2.7 on 2021-10-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='floor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='floors.floor'),
        ),
    ]
