# Generated by Django 3.2.7 on 2021-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('floor_levels', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2')], max_length=2)),
            ],
        ),
    ]
